k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: cd173aa8-f097-573e-9101-75c5ae55654e
    cluster_name: AES Smoke Tests - Yaml
- manifest_path: /manifests
  cluster_info:
    cluster_id: 7a833abf-56f9-506e-a730-02324d31b2ce
    cluster_name: AES Smoke Tests - Helm
